### ISSUE TITLE
Have problem with .cl3

### ISSUE THREAD

**Issue by Hocorog** [u3shit/neptools#16] opened 2021-01-03 16:54 UTC
I'm trying to translate Megadimension Neptunia VIIR into Russian and when translating, I met with such a problem:
![image](https://user-images.githubusercontent.com/76913809/103484058-a2ee4e00-4e0d-11eb-895c-8148e12a6fa2.png)

The event is not exported. It made on the game engine (Orochi), and it seems that neptools does not support it.

**Comment by u3shit** [comment] 2021-01-04 01:37
It looks like VIIR uses some new format not supported by neptools. I never tried VIIR and neptools is pretty much on life support atm. If you can drop the file here I might be able to look into it, but no promises.

**Comment by Hocorog** [comment] 2021-01-04 06:18
[02959.zip](https://github.com/u3shit/neptools/files/5763272/02959.zip)

**Comment by u3shit** [comment] 2021-01-05 20:47
I took a quick look and it's unfortunately not that simple. Does it happen with other files?

**Comment by Hocorog** [comment] 2021-01-05 21:12
Yes, it is. Here are some more examples. There are both imported text from VIIR and Death end re;Quest, and non-export files from both games (both games on the same engine).
[Text and unexported cl3.zip](https://github.com/u3shit/neptools/files/5772610/Text.and.unexported.cl3.zip)

**Comment by u3shit** [comment] 2021-01-09 03:35
[test.zip](https://github.com/u3shit/neptools/files/5790109/test.zip)
Test this version, especially that it still works after changing text and reimporting. I'll make a proper commit tomorrow, too late now.

**Comment by Hocorog** [comment] 2021-01-09 10:57
After importing the text, the cutscene stopped working. But the interface works in it.
And after exporting and importing cl3 files, everything works, but if you import again, an error will appear in the DERQ files. Export also stopped working. VIIR doesn't have that.
![image](https://user-images.githubusercontent.com/76913809/104089560-e0316080-5291-11eb-804b-f426ab48d18d.png)
![image](https://user-images.githubusercontent.com/76913809/104089589-fa6b3e80-5291-11eb-87a2-6af694c737ee.png)
![image](https://user-images.githubusercontent.com/76913809/104089614-21297500-5292-11eb-9bf6-4d0161d142b6.png)
![image](https://user-images.githubusercontent.com/76913809/104089621-2d153700-5292-11eb-95e5-199d71046b1a.png)
[CONTENTS.zip](https://github.com/u3shit/neptools/files/5790509/CONTENTS.zip)

**Comment by u3shit** [comment] 2021-01-09 14:04
I think I've found the bug that broke the DERQ reimport, but I have no idea why doesn't VIIR work. I guess I'll have to get that game...

**Comment by Hocorog** [comment] 2021-01-09 16:41
I can share with the tool that I used when packing text into games and the archive with VIIR data, if you need it.

**Comment by u3shit** [comment] 2021-01-10 01:51
I think I'll have to get the game, just looking at the data files is not enough. But if you have a savegame from where that broken cutscene is easily accessible, that would help.

**Comment by Hocorog** [comment] 2021-01-10 03:37
Here. I was checking events from the gallery:
First slot. Memories => Events => View From Up High 1 (The very first cutscene on the engine)
[774511.zip](https://github.com/u3shit/neptools/files/5792166/774511.zip)

**Comment by u3shit** [comment] 2021-01-10 14:22
Oh, I see now, they changed everything. I'm surprised it still has CL3s inside. So I think I'll need the tool to pack/unpack those dat files, I'd rather not figure out that format too if not required.

**Comment by Hocorog** [comment] 2021-01-10 14:43
The tools unpack the archive next to the file, so it's worth putting it in a separate folder. Unpacks without any structure, so there will be more than 3000 files in the folder. The DAT file to unpack is GxArchivedFile063.dat - there is text from cl3 in English and Chinese versions. The English version starts with 02953. CL3 and ends with 03583. CL3.

**Comment by u3shit** [comment] 2021-01-11 01:15
I've managed to reproduce this problem with the game, but not much, I'll have to dig deeper. In the meantime, could you check that the other files that exported originally correctly do work? Make sure you add or remove enough text so that the .cl3 file size changes.

**Comment by Hocorog** [comment] 2021-01-11 12:04
Everything works fine. Also checked .gbin and .gstr files, but did not replace a couple of lines there. It seems that everything works fine there.
Do I need to check files from DERQ?
![image](https://user-images.githubusercontent.com/76913809/104178779-b6607100-542c-11eb-834c-66df2cedea35.png)
![image](https://user-images.githubusercontent.com/76913809/104178849-cbd59b00-542c-11eb-82e1-4120875317f3.png)
![image](https://user-images.githubusercontent.com/76913809/104180385-de50d400-542e-11eb-8f04-0424fd3e1d38.png)

**Comment by u3shit** [comment] 2021-01-11 21:02
Try this one: https://jenkins.neptards.moe/job/neptools_build_test/48/compiler=clang-msvc,mode=rel/
Please make sure you start over with the original cl3 files, the cl3 files generated by the previous build are probably broken.

![v2r 2021-01-11 21-34-32-61](https://user-images.githubusercontent.com/17014489/104237547-80d17d00-5458-11eb-8cfd-d5ca9d316f5a.png)

**Comment by Hocorog** [comment] 2021-01-11 22:13
Cutscenes are perfectly unpacked. But the rest of the events in cl3 are not unpacked due to a bug that was previously in DERQ.

![image](https://user-images.githubusercontent.com/76913809/104243388-4f6da700-5482-11eb-93e3-8d087f134ce4.png)
![image](https://user-images.githubusercontent.com/76913809/104243434-601e1d00-5482-11eb-8488-bed34c05f14f.png)

And I also wanted to know about the error that was in version 0.3.7. When unpacking some events from DERQ, some did not want to be imported back, creating a separate file in the folder with a random extension that began with .cl3
I tried to pack it into the game, and everything worked. However, after not this event was not unpacked.

![image](https://user-images.githubusercontent.com/76913809/104244271-e2f3a780-5483-11eb-869b-a178637159ad.png)
![image](https://user-images.githubusercontent.com/76913809/104244309-f7d03b00-5483-11eb-9001-66302a6ff6d2.png)
![image](https://user-images.githubusercontent.com/76913809/104244373-19312700-5484-11eb-9f0d-34a93a68dc73.png)

**Comment by u3shit** [comment] 2021-01-11 22:20
Is that 02952.CL3 the original one? The previous build could fuck up the file, please reextract from the original game data and try again.
That random name file: it's a temp file normally deleted by stcm-editor, but if it crashes it can leave it behind sometimes. You can delete it.

**Comment by Hocorog** [comment] 2021-01-11 22:37
This file is original. I specifically deleted the DAT file and downloaded it again, and then unpacked it. The problem is not only with 02952.CL3, but with the rest too.
[CL3Files.zip](https://github.com/u3shit/neptools/files/5798664/CL3Files.zip)

And again about that random file: it did not replace the original one. It looks like the stcm-editor was crashing before it could be replaced. I manually renamed and packed it. Well, for me it's not so critical if everything works. This happens with certain events. Thanks for the answer.

**Comment by u3shit** [comment] 2021-01-12 01:11
Oh, sorry, it was a different CL3, I mixed it up 02959. Anyway, I pushed a fix, a build should show up on this URL eventually
https://jenkins.neptards.moe/job/neptools_build_test/compiler=clang-msvc,mode=rel/50/

**Comment by Hocorog** [comment] 2021-01-12 15:25
Everything unpacked and packed perfectly! Thank you so much for your help, now you can safely translate the game!

![image](https://user-images.githubusercontent.com/76913809/104334292-fa7a7100-5513-11eb-8c10-6c250222b709.png)
![image](https://user-images.githubusercontent.com/76913809/104334324-0403d900-5514-11eb-9690-3a31b41d864a.png)

**Comment by u3shit** [comment] 2021-01-15 00:19
Closing this, feel free to reopen if other issues pop up.
On an unrelated note, I should really make a release soon.

**Closed by u3shit** 2021-01-15 00:19 UTC

**Comment by Hocorog** [comment] 2021-01-22 11:39
Hello.
I have a problem with the .CL3 files again. The program unpacks everything perfectly, but in some events of Death and re;Quest there is an event in which it is necessary to make a choice, the variants of which I also want to translate.
![20210122154900_1](https://user-images.githubusercontent.com/76913809/105484871-dd8d2d00-5ccd-11eb-8144-58bb0294a090.jpg)

The selection options are located in the same CL3 file as the event itself. The text is unpacked, but the selection itself is not.
![image](https://user-images.githubusercontent.com/76913809/105484980-07465400-5cce-11eb-9c3c-ffcae825fd5d.png)

Using Notepad++, I tried to translate the options, but the game did not display the changed text.
![20210122161021_1](https://user-images.githubusercontent.com/76913809/105485429-b08d4a00-5cce-11eb-8d2b-dc66622cac9d.jpg)

Is there any way to get this text out of there? If there is, can you help? And is there anything I can do here?
